import type { CampaignSummary, Company, Opportunity } from "./types";

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-xpto-obra",
    title: "Implantação Obra na Mão",
    companyId: "company-xpto",
    companyName: "Construtora XPTO",
    leadName: "João Silva",
    leadPhone: "5516999991001",
    stage: "proposal",
    estimatedValue: 4800,
    owner: "Marcos",
    nextAction: "Follow-up da proposta",
    nextActionAt: "2026-09-08T13:00:00.000Z",
    campaignId: "campaign-sp-september",
    campaignName: "Construtoras SP — Setembro",
    awaitingHuman: true,
    qualification: "Fit alto",
    source: "Planilha comercial",
    createdAt: "2026-09-02T12:00:00.000Z",
  },
  {
    id: "opp-aurora-demo",
    title: "Demonstração gestão de obra",
    companyId: "company-aurora",
    companyName: "Aurora Engenharia",
    leadName: "Mariana Costa",
    leadPhone: "5516999991002",
    stage: "meeting",
    estimatedValue: 3200,
    owner: "Victor",
    nextAction: "Realizar demonstração",
    nextActionAt: "2026-09-07T16:30:00.000Z",
    campaignId: "campaign-sp-september",
    campaignName: "Construtoras SP — Setembro",
    qualification: "Fit médio",
    source: "Campanha outbound",
    createdAt: "2026-09-01T15:00:00.000Z",
  },
  {
    id: "opp-nova-replied",
    title: "Avaliação comercial",
    companyId: "company-nova",
    companyName: "Nova Base Construtora",
    leadName: "Carlos Mendes",
    leadPhone: "5516999991003",
    stage: "replied",
    estimatedValue: 2100,
    owner: "Marcos",
    nextAction: "Entender operação atual",
    nextActionAt: "2026-09-06T14:00:00.000Z",
    campaignId: "campaign-ribeirao",
    campaignName: "Ribeirão — Obras verticais",
    awaitingHuman: true,
    qualification: "Em diagnóstico",
    source: "Importação XLSX",
    createdAt: "2026-09-03T09:20:00.000Z",
  },
  {
    id: "opp-atlas-qualified",
    title: "Gestão de equipes de campo",
    companyId: "company-atlas",
    companyName: "Atlas Instalações",
    leadName: "Fernanda Alves",
    leadPhone: "5516999991004",
    stage: "qualified",
    estimatedValue: 3900,
    owner: "Victor",
    nextAction: "Agendar diagnóstico",
    nextActionAt: "2026-09-09T11:00:00.000Z",
    campaignId: "campaign-ribeirao",
    campaignName: "Ribeirão — Obras verticais",
    qualification: "Fit alto",
    source: "Outbound",
    createdAt: "2026-09-03T17:10:00.000Z",
  },
  {
    id: "opp-horizonte-negotiation",
    title: "Pacote multiobra",
    companyId: "company-horizonte",
    companyName: "Horizonte Obras",
    leadName: "Renato Lima",
    leadPhone: "5516999991005",
    stage: "negotiation",
    estimatedValue: 7800,
    owner: "Marcos",
    nextAction: "Revisar condições comerciais",
    nextActionAt: "2026-09-10T15:00:00.000Z",
    campaignId: "campaign-key-accounts",
    campaignName: "Contas estratégicas",
    qualification: "Fit alto",
    source: "Indicação",
    createdAt: "2026-08-28T11:00:00.000Z",
  },
  {
    id: "opp-prisma-contacted",
    title: "Primeiro diagnóstico",
    companyId: "company-prisma",
    companyName: "Prisma Construções",
    leadName: "Aline Rocha",
    leadPhone: "5516999991006",
    stage: "contacted",
    estimatedValue: 1800,
    owner: "Victor",
    nextAction: "Aguardar resposta",
    nextActionAt: "2026-09-11T10:00:00.000Z",
    campaignId: "campaign-sp-september",
    campaignName: "Construtoras SP — Setembro",
    source: "Campanha outbound",
    createdAt: "2026-09-04T10:00:00.000Z",
  },
];

export const mockCompanies: Company[] = [
  { id: "company-xpto", name: "Construtora XPTO", city: "Ribeirão Preto", segment: "Construção", leadCount: 2, opportunityCount: 1, pipelineValue: 4800 },
  { id: "company-aurora", name: "Aurora Engenharia", city: "Sertãozinho", segment: "Engenharia", leadCount: 1, opportunityCount: 1, pipelineValue: 3200 },
  { id: "company-nova", name: "Nova Base Construtora", city: "Ribeirão Preto", segment: "Construção", leadCount: 1, opportunityCount: 1, pipelineValue: 2100 },
  { id: "company-atlas", name: "Atlas Instalações", city: "Franca", segment: "Instalações", leadCount: 1, opportunityCount: 1, pipelineValue: 3900 },
  { id: "company-horizonte", name: "Horizonte Obras", city: "São Paulo", segment: "Construção", leadCount: 3, opportunityCount: 1, pipelineValue: 7800 },
  { id: "company-prisma", name: "Prisma Construções", city: "Campinas", segment: "Construção", leadCount: 1, opportunityCount: 1, pipelineValue: 1800 },
];

export const mockCampaigns: CampaignSummary[] = [
  { id: "campaign-sp-september", name: "Construtoras SP — Setembro", status: "running", audience: 850, sent: 394, replied: 87, qualified: 24, opportunities: 8, won: 3, failed: 18, startedAt: "2026-09-01T12:00:00.000Z" },
  { id: "campaign-ribeirao", name: "Ribeirão — Obras verticais", status: "running", audience: 240, sent: 173, replied: 51, qualified: 17, opportunities: 6, won: 2, failed: 7, startedAt: "2026-09-03T12:00:00.000Z" },
  { id: "campaign-key-accounts", name: "Contas estratégicas", status: "paused", audience: 45, sent: 45, replied: 19, qualified: 9, opportunities: 5, won: 1, failed: 2, startedAt: "2026-08-27T12:00:00.000Z" },
];
